language: node_js

node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"

services:
  - mongodb

before_script:
  - npm install -g bower mocha


install:
  - npm install

after_success:
  - openssl aes-256-cbc -K $encrypted_adb96b79157c_key -iv $encrypted_adb96b79157c_iv -in .travis/warcraft_lfg.pem.enc -out .travis/warcraft_lfg.pem -d
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/warcraft_lfg.pem # this key should have push access
  - ssh-add .travis/warcraft_lfg.pem
  - git remote add deploy ssh://warcraftlfg@warcraftlfg.com/home/warcraftlfg/warcraft-lfg
  - git push deploy